
#server:
#  port: 8083
#  spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/userdb
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#    jpa:
#      database-platform:   org.hibernate.dialect.MySQL8Dialect
#      hibernate:
#        ddl-auto: update